# fly.toml file generated for headless-ghost-brijesh-dev on 2023-03-16T21:40:59+05:30

app = "headless-ghost-brijesh-dev"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "arn"
processes = []

[build]
  image = "ghost:5.38.0"

[env]
  url = "https://headless-ghost-brijesh-dev.fly.dev"  
  database__client = "sqlite3"  
  database__connection__filename = "content/data/ghost.db"  
  database__useNullAsDefault = "true"  
  database__debug = "false"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 2368
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
